                        "SANGO  FIGHTER" ORDER FORM OR FAX SHEET

Name:_________________________________________________________________________________

Address:______________________________________________________________________________

City_____________________________________State_______________ZIP______________________

Country  (if outside USA) ____________________________________________________________

Phone  (optional)_______________________________Circle:   home   or    work


Amount enclosed:  $30.00

NOTE:  Please add $5.00 for postage and handling.  Outside USA add $2 extra.

Make checks payable to "PAI."  Orders shipped within one week.
PAI.
    P.O. Box. 23958           Voice : 414-354-6038
      Suite 289               Fax   : 414-354-7255
     Millaukee. WI
     53223/0958
USER'S COMMENTS

1.  Do you think that the game is: [] Excellent [] Very Good [] Average [] Below Average

2.  The game operation is: [] Very Simple [] Simple [] Acceptable [] Quite Difficult [] Very difficult

3.  The characters in the game are: [] Beautiful [] Quite Beautiful [] Acceptable [] Average [] Below Average

4.  The game graphics are: [] Beautiful [] Quite Beautiful [] Acceptable [] Average [] Below Average

5.  The music and sound effects are: [] Very Good [] Good [] Acceptable [] Average [] Below Average

6.  How would you rate yourself as a player? [] Professional [] Advance [] Intermediate [] Beginner

7.  In your opinion, what are the best and worst features of this game?

    The best feature:____________________________________________________________

    The worst feature:___________________________________________________________

8.  Of the twelve characters in the game, name 3 whom you like most:

    _____________________________________________________________________________

9.  What type of games are you most interested in:

    ______________________________________________________________________________

    Which game gave you a lasting impression?

    ______________________________________________________________________________



10. What other kinds of software would you like to see from Panda Entertainment Tech. Co. Ltd?

    __________________________________________________________________________________________

11. What other activities or related products would you expect "SANGO FIGHTER" to launch?

    __________________________________________________________________________________________

12. Please give your comments on "SANGO FIGHTER" game:





-----------------------------------------------------------------------------------------------
RECEIPT FOR PANDA ENTAINMENT TECH. CO., LTD.

Name:_________________________________________________________________________________

Address:______________________________________________________________________________

City_____________________________________State_______________ZIP______________________

Country  (if outside USA) ____________________________________________________________

Phone  (optional)_______________________________Circle:   home   or    work



