echo off
cls
echo * This will display the file called MAXELL.TXT on your screen, one page
echo * at a time.  If you have an on-line printer attached to your machine,
echo * you can print out this help file by typing:
echo *
echo *                         COPY MAXELL.TXT LPT1:
echo *
echo * (or COPY MAXELL.TXT LPT2: if your printer is plugged in to port LPT2:)
echo *
echo * You can also load this file with most word-processors, as it is a regular
echo * ASCII text file.
echo *
echo * Hold down the CTRL key and press the C key, then answer Y to stop this
echo * listing (to print the file, or load it in to your word-processing program)
echo * any other key will continue.
echo *
pause
cls
echo * Welcome.
echo * 
echo * Below is a brief description of 688 ATTACK SUB.  To run the game, we
echo * suggest you print this document for reference, as it contains several
echo * keyboard commands needed throughout the game.  At any time though, you can
echo * find a list of the key commands available on your screen by pressing F1
echo * (the SPACE BAR advances to the next help screen, ESC exits help).  The
echo * first time you run the game, you might want to start by pressing the F1
echo * key, visit all your sub's stations, and press F1 at each station.
echo * 
echo * BEFORE YOU START...
echo * If you haven't already done so, please make a backup of your 688 ATTACK
echo * SUB disk.  688 ATTACK SUB is not 'copy protected' software, you should
echo * make a backup copy of this disk using DISKCOPY (consult your DOS manual
echo * if you don't know how to use DISKCOPY). Always play from your backup copy!
echo * 
echo * IF YOU DON'T HAVE A HARD DISK:
echo * 1.  Place your 688 ATTACK SUB disk in your floppy disk drive.  
echo * 2.  At a DOS prompt, (A: for instance) type the letter of the floppy
echo *     drive that contains this disk, no space, a colon, then press ENTER.
echo * 3.  Type CD \ then press ENTER.
echo * 4.  Type 688 then press ENTER.
echo * 5.  Follow the intructions you see on the screen.
echo * 
pause
cls
echo * IF YOU DO HAVE A HARD DISK:
echo * You can copy all the files on your 688 disk to your hard disk.  We have
echo * provided INSTALL.BAT, which will copy all the files from this disk onto a
echo * subdirectory called MAXELL at the root of your hard drive.
echo * 
echo * 1.  Place your 688 ATTACK SUB disk in your floppy disk drive.
echo * 2.  At a DOS prompt, (A: for instance) type the letter of the floppy drive
echo *     that contains this disk, no space, a colon, then press ENTER.
echo * 3.  Type CD \ then press ENTER.
echo * 4.  Type INSTALL, then press ENTER.
echo * 5.  Follow the intructions you see on the screen.
echo * 6.  Once INSTALL has finished, type 688 then press ENTER.
echo * 7.  Follow the intructions you see on the screen.
echo * 
echo * ONCE THE GAME IS LOADED...
echo * You will be asked to select between two scenarios.  We suggest you start
echo * with scenario one, the training exercise. Type the number of the scenario
echo * you would like to play.  First you will receive a mission description,
echo * your mission orders, and then you will find yourself at the Con (control
echo * room) of a 688 ATTACK SUB (688 is the hull number of the USS Los Angeles,
echo * the first of this class of nuclear attack submarines). The game is paused
echo * whenever you are at the Con, so there is no rush.  You should press F1 to
echo * get help.  The Con is where you access different control areas (stations)
echo * of your sub, including the STATUS SCREEN, the SHIP'S CONTROL PANEL, the
pause
cls
echo * PERISCOPE, the NAVIGATION BOARD,  the WEAPONS CONTROL PANEL, and the
echo * SONAR ROOM.
echo * 
echo * FIRST, THE BASICS...
echo * Our interface is very versatile.  The interface is divided into levels. 
echo * At the top level is the CON.  The Con provides access to the next level
echo * down, called STATIONS (Stations can be rooms or panels). At every Station
echo * are FUNCTION BUTTONS, INDICATORS, and a DISPLAY SCREEN. The function
echo * buttons are grouped into areas of related functions (all the rudder
echo * positions are a group for instance).  All functions have 'hot spots'
echo * associated with them.  Hot spots are areas that perform a function if you
echo * press ENTER or a mouse button while at that location. There are many ways
echo * you can select hotspots.  Choose whatever suits your style...
echo * 
echo * The TAB key will move you between all the groups available on your screen.
echo * The LEFT and RIGHT arrow keys will move between all positions inside a
echo * group. The UP and DOWN arrow keys will move to every position on the
echo * screen, regardless of groupings.  Press ENTER to make a selection.
echo * 
echo * There are QUICK KEY assignments for most functions.  Press the letter 
echo * associated with the function, and your cursor will go directly there. 
echo * Often the QUICK KEY is the first letter of the function, pressing F1 at a
echo * station will list the assignments (if a function has a QUICK KEY
echo * assignment, it is printed in bold after the colon next to the function
pause
cls
echo * name in the help box).  Press ENTER to make the selection.  
echo * 
echo * The FUNCTION KEYS are assigned only to the stations, F2 through F8.  F1 
echo * gives you HELP on every screen.
echo * 
echo * A MOUSE (with a Microsoft(TM)-compatible mouse driver) will move your cursor 
echo * anywhere on the station screen.  When you are over a hot spot, your cursor
echo * will change appearance.  Press any button on the mouse to select that 
echo * function.
echo * 
echo * The NUMBER keys across the top of your keyboard are assigned to function 
echo * groups on each screen, and the groups are numbered top-to-bottom, 
echo * left-to-right.  Pressing a number will move you directly to the assigned 
echo * group.  Since the screens vary slightly, the number assignments can vary.
echo * (the 3 key will not always take you to the TARGET button for instance)
echo * Press ENTER to make the selection.
echo * 
echo * All these methods can be used with each other-  You may mouse over to a 
echo * particular button, press ENTER to activate it, go directly to a station
echo * with a FUNCTION KEY, type a QUICK KEY followed by the mouse button to make
echo * another selection.  Beginners should find this easy to try. With practice
echo * you can find the method fastest for you.
echo * 
echo * The stations in 688 ATTACK SUB have much in common.  The similar elements
pause
cls
echo * will be described below.  Other areas are explained in the individual help
echo * screens.   (Press F1 on any screen for help). 
echo * 
echo * 1.  At the very top of the stations are two target information lines.  If
echo * you have selected a target, all known data regarding the target is printed
echo * here. This will help you keep track of what your target is doing as you
echo * move from station to station.
echo * 
echo * 2.  Most of the stations contain a large DISPLAY SCREEN on the left hand 
echo * side.  The display screen is your 'window'.  There are three modes you can
echo * select.  
echo * 
echo * TOP-DOWN.  This presents the world as if you were looking at a map, with
echo * the darker colors indicating deeper water.
echo * 
echo * CONTOUR MAPPING.  This shows you the underwater world as if looking through
echo * a 'window' (Your 688 has been equipped with a device that functions like
echo * a depth finder.  It allows you to look at the actual bottom contours of
echo * the ocean around you.)
echo * 
echo * PERISCOPE.  If your periscope is up, you will see the periscope view in 3D
echo * perspective.  You can see land and ships from here.  If your periscope is
echo * up, you will see the periscope view in place of the contour-mapping view.
echo * 
pause
cls
echo * This display is controlled by the group of nine buttons in the lower left 
echo * corner of your screen.  You may select one of these buttons with the
echo * tab and arrow keys, your mouse, or by pressing the quick key on your
echo * keyboard that matches the button you want to press, below is a description
echo * of the functions of these buttons:  
echo * 
echo * C = Turn on the contour mapping system.  
echo * 
echo * P = Look to port when in contour mapping mode.  
echo * 
echo * S = Look to starboard when in contour mapping mode.  
echo * 
echo * F = Look forward when in contour mapping mode.  
echo * 
echo * T = Turn on top-down map.  
echo * 
echo * I = Zoom in the map when in top-down mode.  
echo * 
echo * O = Zoom out the map when in top-down mode.  
echo * 
echo * B = Turn on/off bottom contours on the top-down map.  
echo * 
echo * H = Turn on/off Head-up-display
echo * 
pause
cls
echo * The Head-up-display consists of two gauges.  At the top of the display
echo * screen is the compass bar, which shows your current heading.  Along the
echo * right side of the display screen is a depth gauge, calibrated from 0 to
echo * more than 2000 feet.  The left edge of the depth gauge shows two markers.
echo * The dark marker shows where the bottom is, and the light marker shows your
echo * ship's depth (never let the light marker hit the dark marker!)
echo * 
echo * Several things can appear on the display.  
echo * 
echo * A BOX at the center of the display:  That's you.  You are placed in the
echo * center of the display whenever possible.  
echo * 
echo * X's:  an 'X' marker denotes a sonar contact.  The X marker is special.  It
echo * means that all you know about this contact is its bearing (bearing is the
echo * contact's position in degrees relative to north.  For instance, bearing
echo * 90 is like saying 'due east').  You do NOT know how far away it is!  If
echo * you change map zoom (using the top-down map) the X's always appear to be
echo * the same distance away.  As soon as the sonar man can figure out how far
echo * away the target is, the X will change to the first available letter.  
echo * 
echo * LETTERS: represent 'hard' contacts.  Your sonar man will assign a letter
echo * to each contact it can locate.  Once a contact has been located, a couple
echo * of things happen.  First, sonar starts tracking the object, leaving black
echo * dots behind the contact as it moves.  This gives you an idea of what
pause
cls
echo * direction a contact is moving.  The second thing sonar does is to analyze
echo * the audio spectrum of the contact, and try to identify the class and
echo * possibly the actual vessel's name.  If you TARGET the contact, this
echo * information is posted at the top of the screen as it is gathered, and the
echo * tracking markers for that contact will change color. 
echo * 
echo * NUMBERS:  are placed as you set waypoints at the navigation board.  See
echo * the help screen (F1) at the nav board for a complete description.
echo * 
echo * At the bottom of the display screen your course (CRS), speed (SPEED), and
echo * depth (DEPTH) are constantly displayed. Your course is printed in degrees
echo * (90 is east), your speed in knots, and your depth in feet.
echo * 
echo * 3.  The TARGET button appears on several screens, and allows you to select
echo * contacts for attack.  Once you have hit the TARGET button, a cursor appears
echo * on the display screen (regardless of what mode the display is in).  The
echo * TAB key will cycle through the available contacts, (or you can use the
echo * arrow keys, the mouse, or type the letter of contact that have been
echo * assigned letters to place the cursor) and when the cursor is in the right
echo * position, (we suggest using the TAB key to do this, it seems the easiest)
echo * you will see the contact information updated on the target information
echo * line at the top of your screen. You can use this feature to examine all
echo * your contacts to decide which ones you should (and shouldn't) attack.
echo * 
pause
cls
echo * 4.  At the bottom of your screen there are two lines of text.  The bottom
echo * line is the situation line, which always contains your map coordinates,
echo * and the time (since you started the scenario).  The upper line is the
echo * MESSAGE line. Here, the crew keeps you informed of what is happening at
echo * other stations.  If you arm the torpedo tubes from the weapons control
echo * panel for instance, the weapons control officer will report to you when
echo * the torpedo is ready to fire even when you're looking through the
echo * periscope.
echo * 
echo * IT'S TIME TO CHECK OUT YOUR SUB...   You're on the Con of the Los Angeles. 
echo * We recommend that you go to each station and press F1.  Learn about each
echo * station by reading the help screens.  Press the space bar to advance to
echo * the next HELP screen.  In the training scenario you start at periscope
echo * depth, with all engines stopped.  Somewhere nearby are three
echo * decommissioned warships that you have been ordered to destroy.  We suggest
echo * you go to the periscope, raise it, and take a look around (don't leave the
echo * periscope up too long though, because you may be detected).  From the
echo * periscope you may want to go to the weapons control panel to load some
echo * torpedoes.  Next, try going to the ship's control panel and set engines
echo * forward to 1/4 speed.  While the torpedoes are being armed, and the ship is
echo * accelerating, set a waypoint at the navigation board in the direction of
echo * your targets (they probably show up as X's, but be aware that whales,
echo * schools of shrimp and fish can show up as contacts.  As you head in the
echo * direction of the X's, the signals become stronger, and it becomes easier
pause
cls
echo * for sonar to determine what they are (remember though, you can't hear
echo * anything behind your sub, nor can your opponents hear behind their
echo * vessels).  Once an X is resolved, it will be replaced by a letter. Target
echo * that letter, and after a while you may get an identification.  If the
echo * periscope is still up, you should get identification immediately, but
echo * remember that beyond a few miles, ships are below the horizon.
echo * 
echo * When the display screen is in contour mapping mode, lettered contacts are 
echo * represented by circles.  Larger circles mean closer contacts.  When
echo * lettered contacts are very far away, only the letter will be displayed. On
echo * EGA, MCGA and VGA screens lettered contacts are assigned a color-  blue
echo * for underwater, green for surface, and red for weapons (they emit very
echo * high frequency sounds, so they are easy to identify)
echo * 
echo * Good hunting!
echo * 
echo * In the second scenario, you are being tailed by a Soviet Victor III class
echo * submarine, and your orders are to escape detection. Complicating the issue
echo * are other vessels, and more clever opponents. You have 15 minutes for this
echo * scenario. If you escape detection for a period of two minutes, the
echo * scenario will end.  You're on your own out here this time, facing new
echo * challenges.
echo * 
echo * Replay both scenarios.  They play differently, with new starting
pause
cls
echo * locations, and different commanders on the other vessels.  Once you have
echo * mastered the Maxell Special Edition Scenarios, you will be ready to tackle
echo * Electronic Arts' own version, with even more: more scenarios, starting
echo * with a new training mission, ranging to missions of various levels of
echo * challenge, length and experience. There are more weapons that you can use,
echo * more ships to see, more maps to explore, more sounds to hear, more crewmen
echo * to meet.  You'll learn more about the tactics and strategies of submarine
echo * espionage, evasion and destruction, and face veteran enemies with new
echo * tricks of their own.  You will be able to test yourself against your
echo * friends with the MODEM option, or take the Con of the faster,
echo * deeper-diving soviet Alfa class ships.  Play either side of most
echo * scenarios! 
echo * 
echo * Start 688 ATTACK SUB by typing 688 now, and answer the screen display
echo * options.  After you have played a few times, you will remember the number
echo * of your graphics mode.  Typing 688 4 will run 688 ATTACK SUB in MCGA mode
echo * without going to the graphics configuration screen.
echo * 
